apiVersion: apps/v1
kind: Deployment
metadata:
  name: certification
  labels:
    app: certification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certification
  template:
    metadata:
      labels:
        app: certification
    spec:
      containers:
        - name: certification
          image: username/certification:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5